# Generated by Django 3.2 on 2022-02-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220204_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('director', 'director'), ('writer', 'writer'), ('actor', 'actor')], default='actor', max_length=8, null=True, verbose_name='role'),
        ),
    ]
