# Generated by Django 3.2 on 2022-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
